### PR TITLE
[hotfix][postgres] Apply DBZ-5398 postgres connector fix

### PR DESCRIPTION
**Pull request by loserwang1024**
Fix https://github.com/ververica/flink-cdc-connectors/issues/2710, just CP DBZ-5398 in Flink CDC. It resolve the problem of a table without primary key but a functional unique index , such as `create unique index test_tbl_idx on test_table(id, COALESCE(char_c, ''::text));`.

For Increment snapshot mode, In the snapshot phase , table without primary key is not allowed, Thus, when scan.incremental.snapshot.enabled = true, only use 'latest-offset' startup mode to test.

### CODE REVIEW

**Review by sandeepkdeva — APPROVED** [review]

**Comment by sandeepkdeva** [comment]
lgtm.. thanks for the PR

**Comment by sandeepkdeva** [comment]
Hi @loserwang1024 , any update on when this will be merged? Thanks!

**Comment by loserwang1024** [comment]
> Hi @loserwang1024 , any update on when this will be merged? Thanks!
@leonardBang , @ruanhang1993 , CC

**Review by leonardBang — APPROVED** [review]
Thanks @loserwang1024 for the contribution, LGTM. could you rebase to the latest master?

**Comment by loserwang1024** [comment]
@leonardBang , Done it.

**Pull request merged**
