### PR TITLE
[postgres] Reuse pool connection based on database in postgres cdc

### PR DESCRIPTION
**Pull request by loserwang1024**
Fix https://github.com/ververica/flink-cdc-connectors/issues/2428

### CODE REVIEW

**Comment by loserwang1024** [comment]
@TyrantLucifer , CC

**Comment by loserwang1024** [comment]
@ruanhang1993 @whhe , CC, WDYT?

**Review by whhe — APPROVED** [review]
LGTM

**Comment by cobolbaby** [comment]
With the connection pool enabled, which phase of the data synchronization will experience optimization in terms of connection count? Is it during the full synchronization phase? Has there been an estimation of the optimization effect?

**Pull request merged**
