### PR TITLE
[doc]add document for the usage of regex to match multi-tables

### PR DESCRIPTION
**Pull request by LXin96**
add document for the usage of regex to match multi-tables

### CODE REVIEW

**Comment by LXin96** [comment]
@leonardBang Hello. I tried to add some examples to describe the usage of regex to match multi-tables . So I'm sincerely you could review it and give some advices

**Review by leonardBang — COMMENTED** [review]
@LXin96 Thanks for the great work, Could you also add examples for English docs?

**Comment by LXin96** [comment]
@leonardBang OK, I have added some examples for English docs, maybe you could have a look.

**Review by leonardBang — APPROVED** [review]
Thanks @LXin96 for the contribution, LGTM

**Comment by LXin96** [comment]
@leonardBang I'm very glad to do that!

**Pull request merged**
