### PR TITLE
clarify ownership to comply with ASF trademark policies

### PR DESCRIPTION
**Pull request by knaufk**

### CODE REVIEW

**Review by zentol — APPROVED** [review]

**Review by zentol — COMMENTED** [review]
The readme also needs changes.

**Comment by knaufk** [comment]
> The readme also needs changes.

Of course. Done.

**Comment by wuchong** [comment]
@knaufk @zentol , could we remove the "Ververica" in the names and titles? As we discussed before, we would like to move this project to flink-extended group which is more neutral. I think "Ververica" in the names would block us to move it.

**Comment by knaufk** [comment]
@wuchong I don't have strong feelings about the "Ververica" in the name, but I don't understand how it blocks us from moving it to flink-extended. In my understanding the ownership of the code and copyright does not change if it is moved to a different repository. The copyright would still belong to Ververica regardless of the location of the repository and the name.

**Comment by wuchong** [comment]
@knaufk I think it's fine to clarify "Ververica" in the copyright. I just don't think it's a good idea to change the tiltes and names.

**Comment by wuchong** [comment]
@knaufk , if the project is renamed to "Ververica CDC ..." project, it is of course not neutral, and against our original intention to move into flink-extended. Last year, contributors from Cloudera would like to contribute this project, but the main concern is this project is not neutral (has Alibaba and Ververica cloud service background).

**Comment by wuchong** [comment]
@knaufk , if the project is renamed to "Ververica CDC ..." project, it is of course not neutral, and against our original intention to move into flink-extended. Last year, contributors from Cloudera would like to contribute this project, but the main concern is this project is not neutral (has Alibaba and Ververica cloud service background).

**Comment by wuchong** [comment]
@knaufk , if the project is renamed to "Ververica CDC ..." project, it is of course not neutral, and against our original intention to move into flink-extended. Last year, contributors from Cloudera would like to contribute this project, but the main concern is this project is not neutral (has Alibaba and Ververica cloud service background).

**Comment by knaufk** [comment]
Let's leave the discussion of moving the project out of this PR. I have changed the name to "CDC Connectors for Apache Flink". This does not matter in my opinion.

**Comment by zentol** [comment]
I don't understand how this would block a move to flink-extended. At that point you need to prune all mentions of ververica _anyway_; how do 5-6 additional instances _block_ you in any way?

**Comment by wuchong** [comment]
Hi @zentol , my thought is we need to make this project neutral before moving to flink extended. We can rename it again after moving to flink extended, but it would be better to reach consensus at the beginning, and avoid changing titles back and forth. The project might move to flink extended in the next weeks, so I would like we can have an agreement here instead of having another discussion in the near future.

**Review by wuchong — APPROVED** [review]
LGTM

**Comment by leonardBang** [comment]
Thank you for your contribution @knaufk @zentol, I must state my attitude here. What makes me feel a little uncomfortable is that as an open source community, consensus is a minimum principle, rather than two people who have never contributed to project yet suddenly come up with the PR and then AC directly without informing other community contributors who are active or keep going on the project. 

In one word,  I don't mind how many instances or the name of the project, all things we can discuss and then start it. What I really mind is the communication way in an open source community.

**Comment by leonardBang** [comment]
What I said is aimed to the change before jark‘s +1 i.e. your initial commit of this PR，the final change looks good to me too，and I also found a typo and have fixed it. Thanks for your PR again

**Pull request merged**
