### PR TITLE
Update oracle-cdc.md

### PR DESCRIPTION
**Pull request by e-mhui**

### CODE REVIEW

**Review by GOODBOY008 — APPROVED** [review]
LGTM, @e-mhui  Thanks for your contributions.

**Comment by GOODBOY008** [comment]
@e-mhui Can you open a pr to branch `master` ?

**Comment by e-mhui** [comment]
> @e-mhui Can you open a pr to branch `master` ?

ok

**Comment by e-mhui** [comment]
> @e-mhui Can you open a pr to branch `master` ?

The branch `master` has been fixed.

**Pull request merged**
