### PR TITLE
[hotfix][docs] Fix page display errors and improve page Jump mode

### PR DESCRIPTION
**Pull request by rookiegao**
1.Repair page display

2.Page Jump can jump normally in my local and GitHub tests, but it can't jump normally in the official website page. Therefore, I changed the jump related code. I can test the jump here, but I can't guarantee whether the official website page can jump normally

@leonardBang 
I need help

### CODE REVIEW

**Comment by leonardBang** [comment]
@rookiegao The display issue is due to missed blank lines, I think you've fixed it. About the link that contains Chinese you can use in following way: 
```

这是一个中文锚点测试[注意事项](#a-id-custom-text-a)


<a id="custom text">注意事项</a>
--------------------------

```

**Comment by rookiegao** [comment]
> 

I hope there is a practical case. The above reference does not work in my local test

The following is a practical case:
```
<div class="wy-table-responsive">
<table class="colwidths-auto docutils">
    <thead>
      <tr>
        <th class="text-left" style="width:30%;">MySQL type<a href="https://dev.mysql.com/doc/man/8.0/en/data-types.html"></a></th>
        <th class="text-left" style="width:10%;">Flink SQL type<a href="{% link dev/table/types.md %}"></a></th>
        <th class="text-left" style="width:60%;">NOTE</th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <td>
       GEOMETRY<br>
       POINT<br>
       LINESTRING<br>
       POLYGON<br>
       MULTIPOINT<br>
       MULTILINESTRING<br>
       MULTIPOLYGON<br>
       GEOMETRYCOLLECTION<br>
      </td>
      <td>
        STRING
      </td>
      <td>
      MySQL 中的空间数据类型将转换为具有固定 Json 格式的字符串。请参考 MySQL <a href ="#空间数据类型映射">
      空间数据类型映射</a>
       章节了解更多详细信息。               
      </td>
    </tr>
    </tbody>
</table>
</div>

### 空间数据类型映射
```

This is the example of Chinese anchor you provided:
```
这是一个中文锚点测试[空间数据类型映射](#a-id-custom-text-a)

<a id="custom text">空间数据类型映射</a>
```

How to apply this example to the above case？

**Comment by leonardBang** [comment]
@rookiegao Could you investigate the link in html element of markdown like `<div> </div>`  is different with others?

**Comment by rookiegao** [comment]
> @rookiegao Could you investigate the link in html element of markdown like `<div> </div>` is different with others?

@leonardBang 

Modify the previous writing

image

Revised writing

image

image

Both writing methods are recognized by markdown (preview in GitHub source code can successfully jump to anchor point).

However, the first type of HTML does not know what it means. HTML recognizes the second type.

That is to say, there should be no problem with my current modification.

Jump link before modification (HTML unrecognized):

https://github.com/ververica/flink-cdc-connectors/blob/release-2.2/docs/content/connectors/mysql-cdc(ZH).md#%E7%A9%BA%E9%97%B4%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84

Modified jump link (HTML normal recognition):

https://github.com/rookiegao/flink-cdc-connectors/blob/fix_docs_Page_anchor_repair/docs/content/connectors/mysql-cdc(ZH).md#003

**Comment by leonardBang** [comment]
> You can also verify this by clicking these two links. After the first click, you will just jump to the current page. After the second click, you will directly jump to the relevant anchor point.

Thanks @rookiegao for the detail investigation, but I found we need some adjustment even we use `id=003` in my local env, could you have a double check?

image

**Comment by rookiegao** [comment]
> > You can also verify this by clicking these two links. After the first click, you will just jump to the current page. After the second click, you will directly jump to the relevant anchor point.
> 
> Thanks @rookiegao for the detail investigation, but I found we need some adjustment even we use `id=003` in my local env, could you have a double check?
> 
> image

@leonardBang Fixed

**Review by leonardBang — APPROVED** [review]
Thanks @rookiegao for the hotfix, LGTM. Could you also fix the issue in master branch ?

**Comment by rookiegao** [comment]
> 

With pleasure

**Pull request merged**
