### PR TITLE
[docs][mysql] add connection options

### PR DESCRIPTION
**Pull request by eastfisher**
This PR fixes issue #854.

add connection options in mysql connectors docs:

- connection.pool.size
- connect.max-retries

### CODE REVIEW

**Review by leonardBang — APPROVED** [review]
Thanks for the contribution @eastfisher, LGTM.

**Comment by leonardBang** [comment]
@eastfisher Could you also open a PR for `release-2.1` branch?

**Comment by eastfisher** [comment]
> @eastfisher Could you also open a PR for `release-2.1` branch?

Open a new PR.

https://github.com/ververica/flink-cdc-connectors/pull/858

BTW, is there a bot to do this, like [cherry-bot](https://github.com/tidb-incubator/cherry-bot)?

**Comment by leonardBang** [comment]
> BTW, is there a bot to do this, like [cherry-bot](https://github.com/tidb-incubator/cherry-bot)?

Cool! I don't know this robot yet, would you like add a robot for our project?

**Comment by eastfisher** [comment]
> > BTW, is there a bot to do this, like [cherry-bot](https://github.com/tidb-incubator/cherry-bot)?
> 
> Cool! I don't know this robot yet, would you like add a robot for our project? but looks like this need some efforts.

Issue is created: #859, but I'm afraid have no enough time to finish it.

**Comment by leonardBang** [comment]
> Issue is created: #859, but I'm afraid have no enough time to finish it.

Don't worry, it's good enough fine we've recorded this idea.

**Pull request merged**
