### PR TITLE
[WIP][db2] The first draft of DB2-CDC

### PR DESCRIPTION
**Pull request by leonardBang**
The first draft that offers DB2-CDC to capture DB2 table changes.

### CODE REVIEW

**Comment by 1932937611** [comment]
go go go！

**Comment by wanghg158** [comment]
希望2.2支持DB2-CDC

**Comment by waywtdcc** [comment]
go go go！Hope 2.2 support db2 cdc！

**Comment by waywtdcc** [comment]
@leonardBang Hello, do you need to compile and configure DB2 server-side UDF to use this?
image

**Comment by leonardBang** [comment]
> Hey @leonardBang,
> 
> why is this PR still in WIP and not merged back to master? Based on this work we were able to perform CDC for Db2 and it looked fine.

Hey @kisstom. The priority of this PR is relatively low. From the issue list, there are very few user requirement for db2 cdc. Thus we spent effort on other database support like SqlServer and TiDB.

**Comment by githsf** [comment]
image
通过获取的Debezium里面并没有bldrtn执行文件，而通过Find  查找却能在DB2里找到多个bldrtn执行文件，所以应该选择哪个执行文件进行执行

**Comment by githsf** [comment]
@leonardBang

**Pull request closed without merging**
