### PR TITLE
[tests][e2e] add log properties file to e2e tests

### PR DESCRIPTION
**Pull request by loserwang1024**
There is no `log4j2-test.properties` file in e2e tests, so it's hard to find problem in test.Now add `log4j2-test.properties` flie to e2e tests.

### CODE REVIEW

**Comment by loserwang1024** [comment]
@yuxiqian , CC

**Comment by yuxiqian** [comment]
LGTM

Irrelevant to this PR, but I noticed that `log4j2-test.properties` in `flink-connector-db2-cdc` sets it target as `appender.testlogger.target = SYSTEM_OUT` while all other tests use `SYSTEM_ERR`. Should this be fixed, too?

**Comment by loserwang1024** [comment]
@yuxiqian , it seems that two output just with different color, not a big problem.

**Comment by yuxiqian** [comment]
OK, no problems for me.

**Review by whhe — APPROVED** [review]

**Pull request merged**
