### PR TITLE
Support read from specific MySQL Binlog gtid

### PR DESCRIPTION
**Pull request by wangyusong001**
Support read from specific MySQL Binlog gtid.
When reading a highly available MySQL Cluster, a master-slave switch or IP drift occurs and the checkpoint is not updated in a timely way, resulting in a failure to start reading from the checkpoint file due to a change in GTIDs.Since our checkpoints are spaced far apart, this is likely to affect us.
We added the GTID field in the checkpoint file to facilitate our clients to get the accurate GTID.

### CODE REVIEW

**Comment by dutao1** [comment]
赞 👍

**Comment by silvermissile** [comment]
good.
 better to have a unit test

**Comment by leonardBang** [comment]
@wangyusong001 Would you like to support read from specific offset for new MySqlSource(`com.ververica.cdc.connectors.mysql.source.MySqlSource`) ?

**Comment by GOODBOY008** [comment]
> @wangyusong001 Would you like to support read from specific offset for new MySqlSource(`com.ververica.cdc.connectors.mysql.source.MySqlSource`) ?

@leonardBang I am willing to support this feature,If @wangyusong001 do not have time.

**Comment by leonardBang** [comment]
> > @wangyusong001 Would you like to support read from specific offset for new MySqlSource(`com.ververica.cdc.connectors.mysql.source.MySqlSource`) ?
> 
> @leonardBang I am willing to support this feature,If @wangyusong001 do not have time.

I think you can keep @wangyusong001 's contribution and support this feature base on his/her work.

**Comment by GOODBOY008** [comment]
> > > @wangyusong001 Would you like to support read from specific offset for new MySqlSource(`com.ververica.cdc.connectors.mysql.source.MySqlSource`) ?
> > 
> > 
> > @leonardBang I am willing to support this feature,If @wangyusong001 do not have time.
> 
> I think you can keep @wangyusong001 's contribution and support this feature base on his/her work.

Ok,I will.Thanks for your reply!

**Comment by ruanhang1993** [comment]
This has been supported in #1661 . Close this.

**Pull request closed without merging**
