### PR TITLE
[docs] Update the connector download link in the document and Repair …

### PR DESCRIPTION
**Pull request by rookiegao**
…Connector Data Type links

### CODE REVIEW

**Comment by rookiegao** [comment]
@leonardBang @Jiabao-Sun PTAL

**Review by Jiabao-Sun — APPROVED** [review]
Thanks @rookiegao.
LGTM.

**Comment by Jiabao-Sun** [comment]
Hi @rookiegao, can you help split that changes into 2 commit?
I think the changes for data types link is also applies to the master branch.

**Comment by rookiegao** [comment]
> Hi @rookiegao, can you help split that changes into 2 commit? I think the changes for data types link is also applies to the master branch.

done

**Comment by Jiabao-Sun** [comment]
Thanks @rookiegao.
Could you help cherry-pick the second commit for master branch as well?

**Pull request merged**
