### PR TITLE
[bp-3.0][docs] back port doc for Doris/StarRocks connector.

### PR DESCRIPTION
**Pull request by lvyanquan**
back port of https://github.com/ververica/flink-cdc-connectors/pull/2788 https://github.com/ververica/flink-cdc-connectors/pull/2840 https://github.com/ververica/flink-cdc-connectors/pull/2841

### CODE REVIEW

**Comment by lvyanquan** [comment]
@leonardBang @Jiabao-Sun PTAL.

**Comment by Jiabao-Sun** [comment]
Could you help cherry-pick that commits so that we can keep the git history as same as master.

**Comment by lvyanquan** [comment]
> Could you help cherry-pick that commits so that we can keep the git history as same as master.

Done.

**Review by Jiabao-Sun — APPROVED** [review]
LGTM

**Pull request merged**
