### PR TITLE
[oracle] Correct the naming error

### LINKED ISSUE #2404: [oracle cdc] correct the naming error
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

[oracle cdc] correct the naming error 

### Solution

_No response_

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by e-mhui**
[oracle] Correct the naming error
Oracle reads the redo log instead of the binlog.

fix #2404

### CODE REVIEW

**Comment by ruanhang1993** [comment]
@e-mhui There are some compile errors. Please rebase the master branch and fix the compile errors.

**Comment by e-mhui** [comment]
> @e-mhui There are some compile errors. Please rebase the master branch and fix the compile errors.

Thanks, it has been done.

**Review by GOODBOY008 — COMMENTED** [review]
@e-mhui There are remain some in test.

**Comment by e-mhui** [comment]
> @e-mhui There are remain some in test.
> 

Thanks, it has been fixed.

**Review by GOODBOY008 — APPROVED** [review]
LGTM @ruanhang1993 PTAL

**Pull request merged**
