### PR TITLE
[ISSUE-371] Fix enum type cause DataException

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
This problem happens when serialize and deserialize `MySqlSplit`.
Cause debezium `JsonTableChangeSerializer` ignored `defaultValue` and `enumValues` when serializing `Table.Column`.

Rewritten `JsonTableChangeSerializer` as a compromise and it works fine.

Relate to #371

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Sorry, tests fixed.

**Comment by Jiabao-Sun** [comment]
More tests is needed to check for side effects.

**Comment by Jiabao-Sun** [comment]
Sorry @leonardBang , this PR will be closed for the reason as follows.

Simply serializing the default value will not solve this issue, it may cause other type conversion problems.
Before debezium fix it, we may need to use other ways to solve this problem.

**Comment by leonardBang** [comment]
@Jiabao-Sun It makes sense to me, thanks for your effort.

**Comment by luoyuxia** [comment]
@Jiabao-Sun Why simply serializing the default value will not solve this issue? I think it's fine. I wonder what's your concern.

**Comment by Jiabao-Sun** [comment]
> @Jiabao-Sun Why simply serializing the default value will not solve this issue? I think it's fine. I wonder what's your concern.

@luoyuxia Hi, you can see this PR for detail.
https://github.com/debezium/debezium/pull/2671

**Comment by luoyuxia** [comment]
@Jiabao-Sun Thanks~

**Pull request closed without merging**
