### PR TITLE
fix doc 

### PR DESCRIPTION
**Pull request by xixingya**
https://github.com/ververica/flink-cdc-connectors/issues/1750

### CODE REVIEW

**Comment by xixingya** [comment]
> 


> Thanks @xixingya the contribution, I left some comments.
> 
> mysql-cdc.md Line 256
> 
> image
> 
> It seems that it also needs to be changed to long

Thanks, now I fixed it

**Review by rookiegao — APPROVED** [review]
image

**Comment by rookiegao** [comment]
@Jiabao-Sun PTAL

**Review by Jiabao-Sun — APPROVED** [review]
Thanks @xixingya @rookiegao for the great work.
LGTM.

**Pull request merged**
