### PR TITLE
[hotfix][cdc-connector][mysql] skip SchemaChangeEvents that were not included in capturedTableFilter.

### PR DESCRIPTION
**Pull request by lvyanquan**
This closes https://github.com/ververica/flink-cdc-connectors/issues/2981.

### CODE REVIEW

**Comment by lvyanquan** [comment]
@ruanhang1993 @Jiabao-Sun PTAL.

**Comment by lvyanquan** [comment]
Met some failures in CI, will try to fix it.

**Comment by lvyanquan** [comment]
@leonardBang CC.

**Review by leonardBang — APPROVED** [review]
Thanks @lvyanquan for the fix, LGTM

**Comment by steveGuRen** [comment]
@joyCurry30 @leonardBang  Logically, it is considered a bug when I have to read all tables in the schema, and the first execution of "alter table sql" is not triggered. However, since TableDiscoveryUtils loads all tables, it works. But in a SaaS environment, with so many tables(five hundred thousand, a tenant has their own tables), this will cause issues. Because we can't load all tables when have to discover the new Table with query sql by "show create sql " for every table.
So I fix the TableDiscoveryUtils so that just load a table in start or ddl change, and shouEmit logic updates too

**Comment by steveGuRen** [comment]
In the design of TiDB, I find that they take into account the scenario of having a large number of tables in a SaaS environment. Therefore, special attention is given to the performance of DDL operations in such contexts.

**Pull request merged**
