### PR TITLE
[mysql/oracle] Fix the wrong comments in ChunkSplitter

### PR DESCRIPTION
**Pull request by zhaomin1423**
These are some wrong comments.

### CODE REVIEW

**Comment by zhaomin1423** [comment]
cc @ruanhang1993

**Review by ruanhang1993 — APPROVED** [review]
LGTM. Thanks~

**Comment by ruanhang1993** [comment]
@zhaomin1423 Would you mind to change the commit message to '[mysql/oracle] Fix the wrong comments in ChunkSplitter' ?

**Comment by zhaomin1423** [comment]
> @zhaomin1423 Would you mind to change the commit message to '[mysql/oracle] Fix the wrong comments in ChunkSplitter' ?

Done, thanks for your suggestion.

**Pull request merged**
