### PR TITLE
[Rumtime] Hotfix in BinaryRecordDataSerializer with code refractor

### PR DESCRIPTION
**Pull request by xuzifu666**
minor code refractor in BinaryRecordDataSerializer

### CODE REVIEW

**Review by joyCurry30 — APPROVED** [review]
Thanks for the patch! LGTM.

**Comment by xuzifu666** [comment]
> Thanks for the patch! LGTM.



> Thanks for the patch! LGTM.

cc@joyCurry30 CI error seems not related to the changed code

**Comment by xuzifu666** [comment]
> > Thanks for the patch! LGTM.
> 
> > Thanks for the patch! LGTM.
> 
> cc @joyCurry30  CI error seems not related to the changed code

**Review by leonardBang — APPROVED** [review]
Thanks @xuzifu666 for the contribution, LGTM

**Pull request merged**
