### PR TITLE
[issue-314] Support MySQL 5.6 

### PR DESCRIPTION
**Pull request by xiangtao**
1.  Add a MySqlMutiVersionTestBase class to support mysql multi-version container through parameterized test
2. Update MySqlParallelSourceTestBase to support mysql multi-version
3. Update all test case to support mysql 5.6 and 5.7 test
4. Add gtid enable test for all test case

relation: [https://github.com/ververica/flink-cdc-connectors/issues/314](url)

### CODE REVIEW

**Comment by xiangtao** [comment]
Hi, @leonardBang 
Do you have any suggestions?

**Comment by yandavid163** [comment]
翘首以盼5.6

**Comment by which520** [comment]
强烈期待5.6,我都开发完了，才知道不支持我们现有得生产mysql版本

**Comment by leonardBang** [comment]
@xiangtao Could you rebase this PR to master ? I checked the difference between MySQL 5.6 and MySQL 5.7, the main usage of our code should be same.

**Comment by smallx** [comment]
We need you @xiangtao :)

**Review by leonardBang — APPROVED** [review]
Thanks @xiangtao for the contribution, LGTM, I also append a commit to help improve this PR

**Pull request merged**
