### PR TITLE
[docs][oracle] add documents about oracle cdb (#790)

### PR DESCRIPTION
**Pull request by luoyuxia**
Fix for #790

### CODE REVIEW

**Comment by luoyuxia** [comment]
@leonardBang Would you like to help review.

**Comment by leonardBang** [comment]
@luoyuxia Thanks for the contribution, could you validate this in local environment ?

**Comment by luoyuxia** [comment]
@leonardBang yes，I'll validate it as soon as possible.

**Comment by luoyuxia** [comment]
@leonardBang I have validated it in my local environment. Lookforward your review if you're free.

**Review by leonardBang — APPROVED** [review]
Thanks for the contribution @luoyuxia , LGTM

**Pull request merged**
