### PR TITLE
Fix issues(2381)

### PR DESCRIPTION
**Pull request by Malcolmjian**
According to the opinion of the audit, I modified the reference of the method.

### CODE REVIEW

**Comment by ruanhang1993** [comment]
@Malcolmjian Thanks for contributing. There are some checkstyle issues in the PR. Please use the command `mvn spotless:apply` to format your code.

**Comment by Malcolmjian** [comment]
I have formatted the code using the command mvn spottless:apply

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Comment by ruanhang1993** [comment]
Fixed #2381

**Pull request merged**
