### PR TITLE
[mysql] fix deserialization issue on table metadata binlog event

### LINKED ISSUE #2680: [Bug] mysql-cdc 2.5-SNAPSHOT, failed to deserialize MAP event for full_types table
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18

### Flink CDC version

2.5-SNAPSHOT

### Database and its version

mysql  Ver 8.0.33 for macos13.2 on arm64 (Homebrew)

### Minimal reproduce step

# Create Table

```sql
Create Table: CREATE TABLE `test_table_1` (
  `id` bigint unsigned NOT NULL DEFAULT '0',
  `tiny_c` tinyint DEFAULT NULL,
  `tiny_un_c` tinyint unsigned DEFAULT NULL,
  `tiny_un_z_c` tinyint(3) unsigned zerofill DEFAULT NULL,
  `small_c` smallint DEFAULT NULL,
  `small_un_c` smallint unsigned DEFAULT NULL,
  `small_un_z_c` smallint(5) unsigned zerofill DEFAULT NULL,
  `medium_c` mediumint DEFAULT NULL,
  `medium_un_c` mediumint unsigned DEFAULT NULL,
  `medium_un_z_c` mediumint(8) unsigned zerofill DEFAULT NULL,
  `int_c` int DEFAULT NULL,
  `int_un_c` int unsigned DEFAULT NULL,
  `int_un_z_c` int(10) unsigned zerofill DEFAULT NULL,
  `int11_c` int DEFAULT NULL,
  `big_c` bigint DEFAULT NULL,
  `big_un_c` bigint unsigned DEFAULT NULL,
  `big_un_z_c` bigint(20) unsigned zerofill DEFAULT NULL,
  `varchar_c` varchar(255) CHARACTER SET utf8mb3 DEFAULT NULL,
  `char_c` char(3) CHARACTER SET utf8mb3 DEFAULT NULL,
  `real_c` double DEFAULT NULL,
  `float_c` float DEFAULT NULL,
  `float_un_c` float unsigned DEFAULT NULL,
  `float_un_z_c` float unsigned zerofill DEFAULT NULL,
  `double_c` double DEFAULT NULL,
  `double_un_c` double unsigned DEFAULT NULL,
  `double_un_z_c` double unsigned zerofill DEFAULT NULL,
  `decimal_c` decimal(8,4) DEFAULT NULL,
  `decimal_un_c` decimal(8,4) unsigned DEFAULT NULL,
  `decimal_un_z_c` decimal(8,4) unsigned zerofill DEFAULT NULL,
  `numeric_c` decimal(6,0) DEFAULT NULL,
  `big_decimal_c` decimal(65,1) DEFAULT NULL,
  `bit1_c` bit(1) DEFAULT NULL,
  `tiny1_c` tinyint(1) DEFAULT NULL,
  `boolean_c` tinyint(1) DEFAULT NULL,
  `date_c` date DEFAULT NULL,
  `time_c` time DEFAULT NULL,
  `datetime3_c` datetime(3) DEFAULT NULL,
  `datetime6_c` datetime(6) DEFAULT NULL,
  `timestamp_c` timestamp NULL DEFAULT NULL,
  `file_uuid` binary(16) DEFAULT NULL,
  `bit_c` bit(64) DEFAULT NULL,
  `text_c` text CHARACTER SET utf8mb3,
  `tiny_blob_c` tinyblob,
  `blob_c` blob,
  `medium_blob_c` mediumblob,
  `long_blob_c` longblob,
  `year_c` year DEFAULT NULL,
  `enum_c` enum('red','white') CHARACTER SET utf8mb3 DEFAULT 'red',
  `set_c` set('a','b') CHARACTER SET utf8mb3 DEFAULT NULL,
  `json_c` json DEFAULT NULL,
  `point_c` point DEFAULT NULL,
  `geometry_c` geometry DEFAULT NULL,
  `linestring_c` linestring DEFAULT NULL,
  `polygon_c` polygon DEFAULT NULL,
  `multipoint_c` multipoint DEFAULT NULL,
  `multiline_c` multilinestring DEFAULT NULL,
  `multipolygon_c` multipolygon DEFAULT NULL,
  `geometrycollection_c` geomcollection DEFAULT NULL,
  PRIMARY KEY (`id`)
)
```

# Configure flink job
```java
StreamExecutionEnvironment env = StreamExecutionEnvironment.createLocalEnvironment();

env.enableCheckpointing(10_000L);
StreamTableEnvironment tenv = StreamTableEnvironment.create(env);

tenv.executeQuery("CREATE TABLE test_table_1 (`id` DECIMAL(20,0),`tiny_c` TINYINT,`tiny_un_c` SMALLINT,`tiny_un_z_c` SMALLINT,`small_c` SMALLINT,`small_un_c` INT,`small_un_z_c` INT,`medium_c` INT,`medium_un_c` BIGINT,`medium_un_z_c` BIGINT,`int_c` INT,`int_un_c` BIGINT,`int_un_z_c` BIGINT,`int11_c` INT,`big_c` BIGINT,`big_un_c` DECIMAL(20,0),`big_un_z_c` DECIMAL(20,0),`varchar_c` STRING,`char_c` STRING,`real_c` DOUBLE,`float_c` FLOAT,`float_un_c` FLOAT,`float_un_z_c` FLOAT,`double_c` DOUBLE,`double_un_c` DOUBLE,`double_un_z_c` DOUBLE,`decimal_c` DECIMAL(8,4),`decimal_un_c` DECIMAL(8,4),`decimal_un_z_c` DECIMAL(8,4),`numeric_c` DECIMAL(6,0),`big_decimal_c` DECIMAL(65,1),`bit1_c` BOOLEAN,`tiny1_c` BOOLEAN,`boolean_c` BOOLEAN,`date_c` DATE,`time_c` TIME,`datetime3_c` TIMESTAMP(3),`datetime6_c` TIMESTAMP(6),`timestamp_c` TIMESTAMP,`file_uuid` BYTES,`bit_c` BYTES,`text_c` STRING,`tiny_blob_c` BYTES,`blob_c` BYTES,`medium_blob_c` BYTES,`long_blob_c` BYTES,`year_c` STRING,`enum_c` STRING,`set_c` STRING,`json_c` STRING,`point_c` STRING,`geometry_c` STRING,`linestring_c` STRING,`polygon_c` STRING,`multipoint_c` STRING,`multiline_c` STRING,`multipolygon_c` STRING,`geometrycollection_c` STRING,PRIMARY KEY (id) NOT ENFORCED) WITH ( 'connector' = 'mysql-cdc','hostname' = '127.0.0.1','port' = '3306','username' = 'root','password' = '','database-name' = 'test','table-name' = 'test_table_1')");

tenv.executeQuery("SELECT * FROM test_table_1")
```

# Wait for Snapshotting Phase Finish

# Insert Incremental Data

```sql

INSERT INTO test_table_1
VALUES (DEFAULT, 27, 255, 255, 32767, 65535, 65535, 8388607, 16777215, 16777215, 2147483647,
        4294967295, 4294967295, 2147483647, 9223372036854775807,
        18446744073709551615, 18446744073709551615,
        'Hello World', 'abc', 123.102, 123.102, 123.103, 123.104, 404.4443, 404.4444, 404.4445,
        123.4567, 123.4568, 123.4569, 345.6, 34567892.1, 0, 1, true,
        '2020-07-17', '18:00:22', '2020-07-17 18:00:22.123', '2020-07-17 18:00:22.123456',
        '2020-07-17 18:00:22',
        unhex(replace('651aed08-390f-4893-b2f1-36923e7b7400', '-', '')),
        b'0000010000000100000001000000010000000100000001000000010000000100',
        'text', UNHEX(HEX(16)), UNHEX(HEX(16)), UNHEX(HEX(16)), UNHEX(HEX(16)), 2021,
        'red', 'a,b,a', '{
    "key1": "value1"
  }',
        ST_GeomFromText('POINT(1 1)'),
        ST_GeomFromText('POLYGON((1 1, 2 1, 2 2,  1 2, 1 1))'),
        ST_GeomFromText('LINESTRING(3 0, 3 3, 3 5)'),
        ST_GeomFromText('POLYGON((1 1, 2 1, 2 2,  1 2, 1 1))'),
        ST_GeomFromText('MULTIPOINT((1 1),(2 2))'),
        ST_GeomFromText('MultiLineString((1 1,2 2,3 3),(4 4,5 5))'),
        ST_GeomFromText('MULTIPOLYGON(((0 0, 10 0, 10 10, 0 10, 0 0)), ((5 5, 7 5, 7 7, 5 7, 5 5)))'),
        ST_GeomFromText('GEOMETRYCOLLECTION(POINT(10 10), POINT(30 30), LINESTRING(15 15, 20 20))'));


```

# GOT

### What did you expect to see?

incremental data record successfully sinked to target system

### What did you see instead?

java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:168) ~[flink-connector-files-1.18.0.jar:1.18.0]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:117) ~[flink-connector-files-1.18.0.jar:1.18.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
	at com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler.setProducerThrowable(MySqlErrorHandler.java:85) ~[flink-connector-mysql-cdc-2.5-SNAPSHOT.jar:2.5-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1553) ~[flink-connector-mysql-cdc-2.5-SNAPSHOT.jar:1.9.7.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1064) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 1 common frames omitted
Caused by: io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1699588796000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=196, nextPosition=16345945, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1488) ~[flink-connector-mysql-cdc-2.5-SNAPSHOT.jar:1.9.7.Final]
	... 5 common frames omitted
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1699588796000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=196, nextPosition=16345945, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:341) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:313) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:237) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:259) ~[flink-connector-mysql-cdc-2.5-SNAPSHOT.jar:1.9.7.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1051) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 3 common frames omitted
Caused by: java.io.IOException: Unsupported table metadata field type 0
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:52) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:59) ~[flink-connector-mysql-cdc-2.5-SNAPSHOT.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:37) ~[flink-connector-mysql-cdc-2.5-SNAPSHOT.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:335) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 7 common frames omitted

### Anything else?

Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1699588796000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=196, nextPosition=16345945, flags=0}

`Unsupported table metadata field type 0`.

This is the crux of the problem. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by qidian99**
close #2680

### CODE REVIEW

**Comment by maver1ck** [comment]
Maybe we should create issue in original repo ?

**Comment by leonardBang** [comment]
> Maybe we should create issue in original repo ?

+1, @qidian99 would you like to file an issue in upstream repo?

**Comment by leonardBang** [comment]
@ruanhang1993 Would you like to help review this issue when you have time ?

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Pull request merged**
