### PR TITLE
[oracle] oracle table source Add missing parameters

### PR DESCRIPTION
**Pull request by fuyun2024**
oracle table source Add missing parameters

### CODE REVIEW

**Review by leonardBang — COMMENTED** [review]
Thanks @fuyun2024  for the fix, Could you also add the configoptions in the connector document?

**Comment by fuyun2024** [comment]
@leonardBang OK

**Review by leonardBang — APPROVED** [review]
Thanks @fuyun2024 for the update, LGTM

**Comment by leonardBang** [comment]
@fuyun2024 Could also open a PR for master branch?

**Pull request merged**
