### PR TITLE
[cdc-pipeline-connector][mysql] Fix precision problem of BIT type conversion

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
Fix precision problem of BIT type conversion.

### CODE REVIEW

**Review by leonardBang — APPROVED** [review]
Thanks @Jiabao-Sun for troubleshooting and fixing this corner case , LGTM, let's wait the ci green.

**Comment by Jiabao-Sun** [comment]
[DBZ-7230](https://issues.redhat.com/browse/DBZ-7230)

https://github.com/debezium/debezium/pull/5076

**Comment by Sukang1002** [comment]
A similar situation is found if a new column of bit type is added to the mysql table, an error "org.apache.flink.table.api.ValidationException: Binary string length must be between 1 and 2147483647 (both inclusive) " 
 may be reported

**Comment by yuxiqian** [comment]
Hi @Sukang1002, I've tried both pipeline connector and source connector and could not reproduce this issue. Could you please kindly share your configuration so we can investigate it further?

**Pull request merged**
