### PR TITLE
[oracle][doc] Fix oracle quick start

### PR DESCRIPTION
**Pull request by GOODBOY008**

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@YesOrNo828 PTAL

**Review by YesOrNo828 — COMMENTED** [review]
@GOODBOY008  I tested local env, but met this exception:
```
java.lang.IllegalArgumentException: Unable to convert to TimestampData from unexpected value '1596103702001' of type java.lang.Long
   at com.ververica.cdc.connectors.oracle.table.OracleDeserializationConverterFactory$2.convert(OracleDeserializationConverterFactory.java:96)
   at com.ververica.cdc.connectors.oracle.table.OracleDeserializationConverterFactory$3.convert(OracleDeserializationConverterFactory.java:117)
   at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema$17.convert(RowDataDebeziumDeserializeSchema.java:653)
```

I think we should change the Flink SQL DDL of table: orders.ORDER_DATE and enriched_orders.ORDER_DATE type to TIMESTAMP(3). And the quickstart would run successfully.

**Comment by GOODBOY008** [comment]
@YesOrNo828 Thank you for your careful check, I had modify code which you said.

**Review by YesOrNo828 — APPROVED** [review]
LGTM

**Comment by GOODBOY008** [comment]
@leonardBang PTAL , Maybe back support to 2.4.x.

**Review by leonardBang — COMMENTED** [review]
Thanks @GOODBOY008 for the contribution and @YesOrNo828 for the review, LGTM.
feel free to merge and backport to `release-2.4` branch.

**Review by leonardBang — APPROVED** [review]

**Pull request merged**
