### PR TITLE
[debezium] bump debezium version to 1.9.2.

### PR DESCRIPTION
**Pull request by GOODBOY008**
[debezium] bump debezium version to 1.9.2.

### CODE REVIEW

**Comment by snuyanzin** [comment]
since there is already 1.9.5 available, does it make sense to update PR with 1.9.5?

**Comment by GOODBOY008** [comment]
> since there is already 1.9.5 available, does it make sense to update PR with 1.9.5?

We will disscus a plan to bump debezium version , it's a huge task.

**Comment by melin** [comment]
Update with the plan ？ @GOODBOY008

**Comment by tigrulya-exe** [comment]
@GOODBOY008 @leonardBang Hello! I'm currently working on upgrading debezium version of cdc connectors local fork to 1.9.5. I've cherry-picked your commit (41f269b7) on 2.3-release branch and added solid amount of changes over it, so I'd like to share my work when I finish. Should I open separate PR or I can add changes here in order to immediately upgrade dbz to 1.9.5?

**Comment by GOODBOY008** [comment]
> @GOODBOY008 @leonardBang Hello! I'm currently working on upgrading debezium version of cdc connectors local fork to 1.9.5. I've cherry-picked your commit ([41f269b](https://github.com/ververica/flink-cdc-connectors/commit/41f269b70403d6167ca8f7562796cc31dd84baea)) on 2.3-release branch and added solid amount of changes over it, so I'd like to share my work when I finish. Should I open separate PR or I can add changes here in order to immediately upgrade dbz to 1.9.5?

@tigrulya-exe Feel free to open separate pr,  I am looking forward to hearing from you.

**Comment by tigrulya-exe** [comment]
@GOODBOY008 I opened PR: #2156

**Comment by GOODBOY008** [comment]
New pr has opened https://github.com/ververica/flink-cdc-connectors/pull/2156 .

**Pull request closed without merging**
