### PR TITLE
[mysql] Support varbinary type as primary key (#869)

### PR DESCRIPTION
**Pull request by fangpengcheng95**
[bug fix] when use varbinary as primary key，it cause ClassCastException [#869 ](https://github.com/ververica/flink-cdc-connectors/issues/869)

### CODE REVIEW

**Comment by leonardBang** [comment]
@fangpengcheng95 Thanks for the contribution, could you add a test for the change?

**Comment by fangpengcheng95** [comment]
Ping @leonardBang PTAL.thx~

**Comment by leonardBang** [comment]
Thanks @fangpengcheng95 for the contribution, LGTM, I also help reorganize the commits and improve the tests to cover the change.

**Review by leonardBang — APPROVED** [review]

**Comment by leonardBang** [comment]
The CI passed, merging...

**Pull request closed without merging**
