### PR TITLE
[pipeline-connector][mysql] fix timestamp with timezone format

### LINKED ISSUE #2950: [Bug] Caused by: java.time.format.DateTimeParseException: Text '2000-01-01T00:00:00+08:00' could not be parsed at index 19
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink-1.18.0

### Flink CDC version

flink-cdc-3.0.0

### Database and its version

mysql 8.0.30-txsql

### Minimal reproduce step

使用cdc整库同步过程中，某个表的字段：`publish_at` timestamp NULL DEFAULT '2000-01-01 00:00:00' COMMENT '课节资源计划发布时间'，同步时报错，当设置【DEFAULT NULL】后，可以正常同步。

### What did you expect to see?

不变更【DEFAULT '2000-01-01 00:00:00'】，也能正常同步

### What did you see instead?

2023-12-29 17:07:01
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
 at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:176)
 at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:107)
 at org.apache.flink.runtime.scheduler.DefaultScheduler.recordTaskFailure(DefaultScheduler.java:285)
 at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:276)
 at org.apache.flink.runtime.scheduler.DefaultScheduler.onTaskFailed(DefaultScheduler.java:269)
 at org.apache.flink.runtime.scheduler.SchedulerBase.onTaskExecutionStateUpdate(SchedulerBase.java:764)
 at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:741)
 at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:83)
 at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:488)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.lambda$handleRpcInvocation$1(PekkoRpcActor.java:309)
 at org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
 at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcInvocation(PekkoRpcActor.java:307)
 at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:222)
 at org.apache.flink.runtime.rpc.pekko.FencedPekkoRpcActor.handleRpcMessage(FencedPekkoRpcActor.java:85)
 at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:168)
 at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33)
 at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29)
 at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
 at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
 at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29)
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
 at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
 at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
 at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229)
 at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
 at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
 at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
 at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
 at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
 at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
 at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
 at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.time.format.DateTimeParseException: Text '2000-01-01T00:00:00+08:00' could not be parsed at index 19
 at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
 at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
 at java.time.Instant.parse(Instant.java:395)
 at java.util.Optional.map(Optional.java:215)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.inferString(DebeziumSchemaDataTypeInference.java:145)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.infer(DebeziumSchemaDataTypeInference.java:77)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.infer(DebeziumSchemaDataTypeInference.java:56)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.lambda$inferStruct$0(DebeziumSchemaDataTypeInference.java:198)
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
 at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
 at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.inferStruct(DebeziumSchemaDataTypeInference.java:199)
 at com.ververica.cdc.connectors.mysql.source.MySqlSchemaDataTypeInference.inferStruct(MySqlSchemaDataTypeInference.java:40)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.infer(DebeziumSchemaDataTypeInference.java:81)
 at com.ververica.cdc.debezium.event.DebeziumSchemaDataTypeInference.infer(DebeziumSchemaDataTypeInference.java:56)
 at com.ververica.cdc.debezium.event.DebeziumEventDeserializationSchema.extractDataRecord(DebeziumEventDeserializationSchema.java:143)
 at com.ververica.cdc.debezium.event.DebeziumEventDeserializationSchema.extractAfterDataRecord(DebeziumEventDeserializationSchema.java:139)
 at com.ververica.cdc.debezium.event.DebeziumEventDeserializationSchema.deserializeDataChangeRecord(DebeziumEventDeserializationSchema.java:105)
 at com.ververica.cdc.debezium.event.SourceRecordEventDeserializer.deserialize(SourceRecordEventDeserializer.java:47)
 at com.ververica.cdc.debezium.event.DebeziumEventDeserializationSchema.deserialize(DebeziumEventDeserializationSchema.java:92)
 at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitElement(MySqlRecordEmitter.java:128)
 at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.processElement(MySqlRecordEmitter.java:110)
 at com.ververica.cdc.connectors.mysql.source.reader.MySqlPipelineRecordEmitter.processElement(MySqlPipelineRecordEmitter.java:119)
 at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:82)
 at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:55)
 at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:160)
 at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:419)
 at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
 at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:562)
 at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:858)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:807)
 at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953)
 at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:932)
 at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746)
 at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
 at java.lang.Thread.run(Thread.java:750)

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by whhe**
Try to fix #2950

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Thanks @whhe for this contribution. It makes sense.
I'm a little curious why this question only appears in MySQL8.
By the way, could you please add some tests in `MySqlFullTypesITCase` ?

**Comment by bingxindan** [comment]
On which version will this bug be fixed? I will download one and test it out

**Comment by whhe** [comment]
> Thanks @whhe for this contribution. It makes sense. I'm a little curious why this question only appears in MySQL8. By the way, could you please add some tests in `MySqlFullTypesITCase` ?

Sure, I will have a try to add a full types test case for it soon.

For the issue cause, now the pipeline connector converts TIMESTAMP to TIMESTAMP_LTZ in [MySqlTypeUtils.java#L194](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/utils/MySqlTypeUtils.java#L194), while the original mysql source connector does not deal with TIMESTAMP WITH TIME ZONE, so it I think should only occur in e2e case.

**Comment by Jiabao-Sun** [comment]
> > Thanks @whhe for this contribution. It makes sense. I'm a little curious why this question only appears in MySQL8. By the way, could you please add some tests in `MySqlFullTypesITCase` ?
> 
> Sure, I will have a try to add a full types test case for it soon.
> 
> For the issue cause, now the pipeline connector converts TIMESTAMP to TIMESTAMP_LTZ in [MySqlTypeUtils.java#L194](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/utils/MySqlTypeUtils.java#L194), while the original mysql source connector does not deal with TIMESTAMP WITH TIME ZONE, so it I think should only occur in e2e case.

Thanks @whhe.

https://github.com/ververica/flink-cdc-connectors/blob/1b643026fe93ed477541dcd7e97001785840a296/flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/column_type_test_mysql8.sql#L108

Change it to `timestamp_c TIMESTAMP(0) NULL DEFAULT '2000-01-01 00:00:00'` can reproduce this problem.

**Comment by whhe** [comment]
Because MySqlValueConverters always uses UTC, so using `Instant.parse` is OK for other cases, here I only changed the parsing related to default value.

**Review by Jiabao-Sun — APPROVED** [review]
LGTM

**Pull request merged**
