### PR TITLE
[docs][pipeline-connector][starrocks] Fix the pictures do not display

### PR DESCRIPTION
**Pull request by banmoy**

### CODE REVIEW

**Comment by banmoy** [comment]
@lvyanquan minor fix. PTAL

**Review by lvyanquan — APPROVED** [review]
LGTM.

**Comment by lvyanquan** [comment]
@leonardBang @Jiabao-Sun CC.

**Review by Jiabao-Sun — APPROVED** [review]
Thanks @banmoy for this contribution.
LGTM.

**Pull request merged**
