### PR TITLE
fix data loss in tidb-cdc when switch from snapshot read to change event read

### PR DESCRIPTION
**Pull request by xieyi888**
Signed-off-by: Yi Xie <xieyi01@rd.netease.com>

Link： https://github.com/ververica/flink-cdc-connectors/issues/1206

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@xieyi888 When I add unit test in pr https://github.com/ververica/flink-cdc-connectors/pull/1632 . I had reproduced this sceno in my added unit test.

**Comment by GOODBOY008** [comment]
@xieyi888 It's great catch ,Thanks for your contributions. When run unit test `com.ververica.cdc.connectors.tidb.table.TiDBConnectorITCase#testRegionChange` with code `waitForSinkSize("sink", 0);` ,will occur data lost.

**Review by GOODBOY008 — APPROVED** [review]
@xieyi888 Thanks for your contributions. LGTM ! This scene Unit test will be added in pr https://github.com/ververica/flink-cdc-connectors/pull/1632 .

**Comment by xieyi888** [comment]
> @xieyi888 Thanks for your contributions. LGTM ! This scene Unit test will be added in pr #1632 .

Thanks for your review

**Comment by xieyi888** [comment]
> @xieyi888 It's great catch ,Thanks for your contributions. When run unit test `com.ververica.cdc.connectors.tidb.table.TiDBConnectorITCase#testRegionChange` with reomove code `waitForSinkSize(

> @xieyi888 It's great catch ,Thanks for your contributions. When run unit test `com.ververica.cdc.connectors.tidb.table.TiDBConnectorITCase#testRegionChange` with reomove code `waitForSinkSize("sink", 1);` ,will occur data lost.

Thanks for your review!

**Pull request merged**
