### PR TITLE
[oceanbase] Remove useless dependency and code of test.

### PR DESCRIPTION
**Pull request by GOODBOY008**
[oceanbase] Remove useless dependency and code of test.

### CODE REVIEW

**Review by whhe — APPROVED** [review]
LGTM

**Review by leonardBang — COMMENTED** [review]
+1

**Review by leonardBang — APPROVED** [review]

**Comment by leonardBang** [comment]
@GOODBOY008 Could you open a backport PR for `release-2.2` branch ?

**Comment by GOODBOY008** [comment]
> @GOODBOY008 Could you open a backport PR for `release-2.2` branch ?

Ok.

**Pull request merged**
