### PR TITLE
[test] specify surefire provider

### LINKED ISSUE #1416: [ci] integrated tests are skipped in some connectors
There seems to be something wrong in integrated tests https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=1903&view=logs&j=75bdd006-2058-55d4-dca6-119badb03732&t=b1a35d0a-8b58-59d5-ca81-b4732574f166

```
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
java.lang.NoSuchMethodError: org.junit.platform.engine.EngineDiscoveryRequest.getDiscoveryListener()Lorg/junit/platform/engine/EngineDiscoveryListener;
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:88)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:44)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:63)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:129)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.getSuites(JUnitPlatformProvider.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeGetter(ReflectionUtils.java:76)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeGetter(ReflectionUtils.java:70)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.getSuites(ProviderFactory.java:145)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.getSuitesIterator(ForkStarter.java:699)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:403)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:293)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

### PR DESCRIPTION
**Pull request by whhe**
fix #1416

### CODE REVIEW

**Comment by whhe** [comment]
There are some errors in mysql connector which are related to #1284 and https://github.com/apache/flink/commit/bf554282567749966ab7d2e5b894de71f7436813, other failures have not been located and I think we can fix them in other PRs.

**Comment by ruanhang1993** [comment]
@whhe Thanks for your PR.
It seems that this PR forces usage of the JUnit 4.7 provider. Maybe this change is enough to fix the problem by now. 
But Flink is promoting the Junit 5 migration in [FLINK-25325](https://issues.apache.org/jira/browse/FLINK-25325). I think we should use the JUnit 5 platform as well.

The problem may lie in the conflict in the dependency. And I find the junit version conflict.
截屏2022-07-28 下午3 58 52

**Comment by whhe** [comment]
> @whhe Thanks for your PR. It seems that this PR forces usage of the JUnit 4.7 provider. Maybe this change is enough to fix the problem by now. But Flink is promoting the Junit 5 migration in [FLINK-25325](https://issues.apache.org/jira/browse/FLINK-25325). I think we should use the JUnit 5 platform as well.
> 
> The problem may lie in the conflict in the dependency. And I find the junit version conflict. 截屏2022-07-28 下午3 58 52

Yes, JUnit provider is forced to be 4.7+ in this PR. I found that the tests of master branch were launched by `junit-platform`, while the JUnit version of Flink 1.14 was 4.13, which means there is something wrong in [provider selection](https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html#provider-selection).


If we specify the JUnit provider here, we can also remove it or update to `junit-platform` when the Flink test utils used in Flink CDC is updated in the future.

**Comment by whhe** [comment]
#1446 would be able to resolve errors in mysql connector tests.

**Comment by ruanhang1993** [comment]
It seems like the `testMetadataColumns` in many connector's `xxxConenctorITCase' fails. I will take a look at this.

**Comment by ruanhang1993** [comment]
> It seems like the `testMetadataColumns` in many connector's `xxxConenctorITCase` fails. I will take a look at this.

Because of this change in Flink(https://issues.apache.org/jira/browse/FLINK-20370), we need to add records whose type is update before when the primary keys of source and sink are different.

**Comment by ruanhang1993** [comment]
#1451 would be able to resolve errors in `testMetadataColumns` tests.

**Comment by leonardBang** [comment]
Thanks @whhe @ruanhang1993 for the great work, but there's a  failed test `PolardbxSourceITCase`, could you take a more look?

**Comment by whhe** [comment]
> Thanks @whhe @ruanhang1993 for the great work, but there's a failed test `PolardbxSourceITCase`, could you take a more look?

Will have a try tomorrow, as today is the last day of my vacation.

**Comment by ruanhang1993** [comment]
> Thanks @whhe @ruanhang1993 for the great work, but there's a failed test `PolardbxSourceITCase`, could you take a more look?

I found that this test will sometimes throw an exception like this and the sqls in `initializePolardbxTables` will not be executed.
截屏2022-08-09 下午3 34 15

If the previous error does not occur, the container may exit with a warning after a few time: `[Warning] [MY-011245] [Server] Plugin mysqlx reported: 'Galaxy session 0x7f970000b850 sid 43 kill pool 0x7f9700011a08.'`. And some test cases will fail because of the exiting of the polarxdb container.

I have not found the reason why this happens.

**Comment by leonardBang** [comment]
The test passed in my local env and the azure CI env after I upgrade the polardb-x docker image version, I doubt this issue is related to the docker image version instead of our codebase, I'll merge this pr now.

Thanks @whhe and @ruanhang1993 for the great work.

**Review by leonardBang — APPROVED** [review]

**Pull request closed without merging**
