### PR TITLE
[issue-329] Fix find min binlog offset wrong value in increment binlog stage

### PR DESCRIPTION
**Pull request by xiangtao**
When all snapshot spit stage finished , it need to create a MySqlBinlogSplit to start up a increment binlog stage .
First need to find a startingOffset position from all assignedSnapshotSplit of snapshot stage.
But it always get BinlogOffset.INITIAL_OFFSET value .

### CODE REVIEW

**Review by leonardBang — COMMENTED** [review]
Thanks @xiangtao for the contribution, the changes looks good, could you add a unit test for this?

**Comment by xiangtao** [comment]
OK @leonardBang

**Comment by xiangtao** [comment]
any suggestions ? @leonardBang

**Review by leonardBang — APPROVED** [review]
Thanks @xiangtao for the great work, LGTM, I append one commit for code cleanup, will merge this soon

**Comment by leonardBang** [comment]
@xiangtao Could you also open a PR to cherry-pick the commit e34ff84a43033b0909d62aaa1722ce322a354b0e to release-2.0 branch?

**Pull request merged**
