### PR TITLE
[oracle-cdc] fix oracle cdc data lose during the snapshot to incremental process

### PR DESCRIPTION
**Pull request by yunqingmoswu**
fix oracle cdc data lose during the snapshot to incremental process.

### CODE REVIEW

**Comment by EMsnap** [comment]
image
please fix format check

**Comment by EMsnap** [comment]
could you please provide a detailed description on this issue ?

**Comment by yunqingmoswu** [comment]
> image please fix format check

done

**Comment by leonardBang** [comment]
Thanks @yunqingmoswu for the contribution, the change looks good to me, could you add a test for this case?

**Comment by loserwang1024** [comment]
> Thanks @yunqingmoswu for the contribution, the change looks good to me, could you add a test for this case?

@leonardBang @yunqingmoswu , 
 It's not easy to add test now.
In https://github.com/ververica/flink-cdc-connectors/issues/2553, I add hooks to do database operations during snapshot split code and also add test in it. However, that PR depends on this PR.Therefore, please merge this PR at first.

**Review by loserwang1024 — APPROVED** [review]

**Pull request closed without merging**
